### ISSUE TITLE
unit test won't clean up db after running

### ISSUE THREAD

**Issue by hesna** [yiisoft/yii2-codeception#7] opened 2015-08-26 11:10 UTC
It's same as [this issue](https://github.com/yiisoft/yii2/issues/9522) from framework main repo. seems like here is a better place for it:

I'm using Yii2 module: (note that `cleanup` is enabled) 
```yml
class_name: UnitTester
modules:
    enabled:
        - Yii2:
            part: ORM
    config:
        Yii2:
            cleanup: true
            configFile: '../config/backend/unit.php'
```

working with `haveRecord()` and `seeRecord()` methods:
```php
    public function testWebsiteInsertion()
    {
        $this->tester->haveRecord(
            Website::className(),
            [
                'title' => 'test site',
                'language' => 'fa',
                'subdomain' => 'test',
                'themeId' => 1
            ]
        );

        $this->tester->seeRecord(
            Website::className(),
            ['subdomain' => 'test']
        );
    }
```
It does not clean up db after running! I traced it down to here `Codeception\Module\Yii2::_after()` :
```php
        if ($this->transaction && $this->config['cleanup']) {
            $this->transaction->rollback();
        }
```
The `if` condition is true and transaction does rollback, but inserted rows do not get removed! I even traced Transaction class in framework core and there were no errors. I'm really stuck, did I miss something? are there other configurations?

**Comment by kaiserfedor** [comment] 2015-10-27 12:13
@hesna Hello, I have the same problem. Have you found the solution?

**Comment by samdark** [comment] 2015-10-27 14:11
We've recently patched Codeception module a bit. Could you try Codeception 2.1-dev?

**Comment by hesna** [comment] 2015-10-27 14:35
@kaiserfedor Hi, sorry I have not. and have not yet tried this :point_up_2:

**Comment by kaiserfedor** [comment] 2015-10-28 03:16
@samdark I've updated Codeception to 2.1.x-dev and problem is still reproduced, unfortunately.
I've tried begin and rollback transaction explicitly in test and it works well, but it's not solution.

**Comment by kaiserfedor** [comment] 2015-10-28 04:08
I solve problem by modified method yiisoft/yii2-codeception/TestCase::mockApplication
https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L105
I added this code to begining of method:
```
if (isset(Yii::$app)) {
    return;
}
```
The problem is Codeception module begin transaction in one db connection and then TestCase::mockApplication create another db connection.

**Comment by samdark** [comment] 2015-10-28 07:14
Are you sure you've checked latest 2.1 branch code? https://github.com/Codeception/Codeception/commit/c90ace2b69ee2332740018ff0489399ed7c89ada

**Comment by kaiserfedor** [comment] 2015-10-28 07:29
@samdark  Yes, of course. This is part of my composer.lock:
```
"name": "codeception/codeception",
            "version": "2.1.x-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/Codeception/Codeception.git",
                "reference": "c90ace2b69ee2332740018ff0489399ed7c89ada"
            },
```
Is it OK?

**Comment by samdark** [comment] 2015-10-28 07:37
@ivokund isn't it the same thing your commit was intended to solve?

**Comment by ivokund** [comment] 2015-10-28 08:41
It's very similar, although not exactly the same thing. https://github.com/Codeception/Codeception/commit/c90ace2b69ee2332740018ff0489399ed7c89ada solved the same issue inside Yii2 connector. So when modules use it to create a testable application mocks (in functional tests), the same database connection is used in every one of these mock applications. Now the module and connector share the DB instance, so the rollbacks work correctly. But this is different, I believe Yii2 connector is not used here at all.

I have two ideas/guesses:

1. `\Codeception\Module\Yii2::getModelRecord` creates a new model object. Is the attached DB instance the same that's used [here](https://github.com/Codeception/Codeception/blob/c90ace2b69ee2332740018ff0489399ed7c89ada/src/Codeception/Module/Yii2.php#L81)? Perhaps it should use the DB instance from the connector (`$this->app->db`) somehow?
2. Does [this](https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L131) interfere with the transaction rollback logic? Probably not.

But I'm not sure in any of this. @Ragazzo can probably shed some light on this.

**Comment by kaiserfedor** [comment] 2015-10-29 05:34
As I wrote above the problem is Codeception module create app instance here:
https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Connector/Yii2.php#L61
And then extension create another app instance here:
https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L120

This way transaction and test use different db connection.

I've created pull request, maybe it would be helpful:
https://github.com/yiisoft/yii2-codeception/pull/12

**Comment by Ragazzo** [comment] 2015-10-29 06:37
why you are using `Yii2` connector in your unit tests ?

**Comment by kaiserfedor** [comment] 2015-10-29 06:54
I'm not using Yii2 connector in my unit tests, I'm just using orm part of Yii2 module for cleanup database after unit tests like it describe in part "ORM modules" here http://codeception.com/docs/09-Data and here http://codeception.com/06-28-2014/unit-testing-with-database.html

**Comment by Ragazzo** [comment] 2015-10-29 07:01
for database cleanup in `Yii2` you can use fixtures as was stated in docs for Yii2, thus you will not run in this problem. The basic workflow for unit-tests:

- run migrate command to make your database schema up to date;
- use fixtures in setUp / tearDown methods to populate schema with needed data or to clean up it;

**Comment by kaiserfedor** [comment] 2015-10-29 07:21
I talk about remove data that have been insert into db while test is executed, not about data from fixture.

**Comment by Ragazzo** [comment] 2015-10-29 07:44
you can do it in `tearDown` anyway, plus you can write your own fixture if needed to remove this data, if it should be removed in other places too

**Comment by kaiserfedor** [comment] 2015-10-29 08:00
Ok, I can do it in tearDown, I know it.  But @hesna and I talk about feature that is  described in official documentation, why should we not use it?

**Comment by Ragazzo** [comment] 2015-10-29 08:17
nope, you can use it but there is a drawback for that, initially it was not designed to use them both since for Yii2 we made fixtures and so on. But your fix will be incorrect for unit tests when you need to mock application for specific purpose in particular in one of the test methods in test case.

**Comment by hesna** [comment] 2015-10-29 08:20
@Ragazzo I was just trying to figure out how things work at the time. you mean this feature works in functional tests? I actually gave up on it and used fixtures instead, but this feature is not working as it's supposed to and others might face with same problem. maybe it's better to get rid of `cleanup` option and make everyone use fixtures for this purpose?

**Comment by Ragazzo** [comment] 2015-10-29 08:27
yes, as for me it is better to remove this feature of `cleanup`, it was introduced by @DavertMik for his purposes when he was working with `Yii2` and transactions rollback, thus it creates a lot of unnecessary questions and issues.

**Comment by ivokund** [comment] 2015-10-29 08:44
Please leave this option at least for functional tests (where it now works correctly). Rollbacks are a lot cleaner and faster way to undo all changes, than unloading fixtures. 

Probably it would help to mention that it's only meant for functional tests. Plus the cleanup flag is currently not mentioned here at all: http://codeception.com/docs/modules/Yii2

**Closed** 2015-10-29 09:03 UTC
Labels: bug
